import { LocalEvent, EmailThread, ScoutLog } from '@/types';

export const INITIAL_EVENTS: LocalEvent[] = [
  {
    id: 'evt-dice-1',
    title: 'Brooklyn Indie Showcase: Live on DICE',
    category: 'music',
    tagline: 'Raw guitar tones & intimate indie vibes in Williamsburg',
    description: "Catch an incredible lineup of local emerging alternative and indie rock acts handpicked for New York music lovers. Experience an immersive night of atmospheric melodies and driving basslines in one of Brooklyn's favorite listening rooms.",
    venueName: 'Brooklyn Made',
    address: '428 Troutman St, Bushwick',
    distanceKm: 2.1,
    coordinates: { lat: 40.7061, lng: -73.9234 },
    dateTime: '2026-09-19T20:00:00Z',
    formattedDate: 'Saturday, Sep 19',
    formattedTime: '8:00 PM - 11:30 PM',
    price: '$18 at door',
    isFree: false,
    matchScore: 97,
    vibeTags: ['#IndieRock', '#BrooklynGigs', '#LiveMusic', '#DICE'],
    organizerName: 'Brooklyn Made Booking',
    organizerEmail: 'booking@brooklynmade.com',
    sourceUrl: 'https://dice.fm/browse/new_york-5bbf4db0f06331478e9b2c59/music/gig/indie',
    firecrawlExtractedAt: 'Just now',
    ticketsRemaining: 30,
    coverImage: 'https://dice-media.imgix.net/attachments/2026-09-02/b2cf4ee8-7618-4c6f-8548-357da91f33e9.jpg?rect=0%2C0%2C1200%2C1200&auto=format%2Ccompress&q=80&w=800&fit=crop',
    outreachStatus: 'none',
  },
  {
    id: 'evt-1',
    title: 'Neon Basement: Underground Indie Showcase',
    category: 'music',
    tagline: 'Lo-fi garage rock, fuzz pedals, and secret DIY basement stage',
    description: 'A curated night of 4 emerging indie rock outfits playing intimate, raw live sets. Analog tape visuals, craft local cider, and limited capacity.',
    venueName: 'The Sub-Cellar Studio',
    address: '428 Industrial Way, District 4',
    distanceKm: 3.4,
    coordinates: { lat: 40.7182, lng: -73.9924 },
    dateTime: '2026-09-19T20:30:00Z',
    formattedDate: 'Saturday, Sep 19',
    formattedTime: '8:30 PM - 1:00 AM',
    price: '$15 / PWYC at door',
    isFree: false,
    matchScore: 98,
    vibeTags: ['#IndieRock', '#Garage', '#DIY', '#Underground'],
    organizerName: 'Julian Vance (Sub-Cellar Collective)',
    organizerEmail: 'booking@subcellarstudio.org',
    sourceUrl: 'https://subcellarstudio.org/calendar/sep-19-indie-showcase',
    firecrawlExtractedAt: '12 mins ago',
    ticketsRemaining: 24,
    coverImage: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=800&q=80',
    outreachStatus: 'none',
  },
  {
    id: 'evt-2',
    title: 'Cobblestone Night Flea & Vinyl Bazaar',
    category: 'market',
    tagline: 'Outdoor courtyard night market with 30+ vintage sellers, crates of vinyl, and live street jazz',
    description: 'Brimming with retro ceramics, 90s vintage garments, rare cassette tapes, Japanese street food stalls, and acoustic performances under fairy lights.',
    venueName: 'The Old Foundry Courtyard',
    address: '14 Ironworks Plaza',
    distanceKm: 6.8,
    coordinates: { lat: 40.7308, lng: -74.0012 },
    dateTime: '2026-09-19T17:00:00Z',
    formattedDate: 'Saturday, Sep 19',
    formattedTime: '5:00 PM - 11:00 PM',
    price: 'Free Entry',
    isFree: true,
    matchScore: 94,
    vibeTags: ['#OutdoorMarket', '#Vinyl', '#Vintage', '#NightMarket', '#FreeEntry'],
    organizerName: 'Mira Solis (Foundry Arts Market)',
    organizerEmail: 'events@foundrymarket.co',
    sourceUrl: 'https://foundrymarket.co/weekend-flea-sep19',
    firecrawlExtractedAt: '28 mins ago',
    ticketsRemaining: undefined,
    coverImage: 'https://images.unsplash.com/photo-1533900298318-6b8da08a523e?auto=format&fit=crop&w=800&q=80',
    outreachStatus: 'none',
  },
  {
    id: 'evt-3',
    title: 'Ephemeral Form: Kinetic Light & Sculpture Opening',
    category: 'art',
    tagline: 'Solo vernissage featuring immersive phosphorescent sculptures and reactive soundscapes',
    description: 'Opening vernissage for sculptor Kaelen Chen. Interactive light sculptures that react to visitor proximity and spatial reverberation. Complimentary natural wine for early arrivals.',
    venueName: 'Gallery Null Space',
    address: '88 Mercer Lane',
    distanceKm: 11.2,
    coordinates: { lat: 40.7418, lng: -73.9892 },
    dateTime: '2026-09-20T19:00:00Z',
    formattedDate: 'Sunday, Sep 20',
    formattedTime: '7:00 PM - 10:30 PM',
    price: 'Free RSVP',
    isFree: true,
    matchScore: 91,
    vibeTags: ['#ArtOpening', '#KineticArt', '#NaturalWine', '#Installation'],
    organizerName: 'Evelyn Gray (Gallery Director)',
    organizerEmail: 'rsvp@nullspacegallery.art',
    sourceUrl: 'https://nullspacegallery.art/exhibits/ephemeral-form',
    firecrawlExtractedAt: '45 mins ago',
    ticketsRemaining: 40,
    coverImage: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=800&q=80',
    outreachStatus: 'none',
  },
  {
    id: 'evt-4',
    title: 'Velvet Horizon: Psych-Rock & Synth Tapestry',
    category: 'music',
    tagline: 'Dual headline of ambient dream-pop and heavy motorik krautrock vibes',
    description: 'Echoing guitar washes, vintage Moog synthesizers, and immersive 16mm analog projector visuals on textured canvas screens.',
    venueName: 'Blackbox Warehouse 9',
    address: '910 Dockside Terrace',
    distanceKm: 8.5,
    coordinates: { lat: 40.7051, lng: -73.9785 },
    dateTime: '2026-09-20T21:00:00Z',
    formattedDate: 'Sunday, Sep 20',
    formattedTime: '9:00 PM - 2:00 AM',
    price: '$20',
    isFree: false,
    matchScore: 89,
    vibeTags: ['#PsychRock', '#SynthWave', '#Visuals', '#LiveGig'],
    organizerName: 'Derrick Moss',
    organizerEmail: 'shows@docksidecollective.net',
    sourceUrl: 'https://docksidecollective.net/events/velvet-horizon',
    firecrawlExtractedAt: '1 hr ago',
    ticketsRemaining: 15,
    coverImage: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=800&q=80',
    outreachStatus: 'none',
  },
  {
    id: 'evt-5',
    title: 'Canal Works Makers Fair & Food Truck Grove',
    category: 'market',
    tagline: 'Over 40 independent jewelers, printmakers, and woodworkers along the canal basin',
    description: 'Family & dog friendly artisan gathering. Artisan bread, wood-fired pizza ovens, artisanal hot sauces, and screenprinting workshops.',
    venueName: 'Canal Basin Park',
    address: 'Canal & 3rd St',
    distanceKm: 14.2,
    coordinates: { lat: 40.6782, lng: -73.9984 },
    dateTime: '2026-09-20T11:00:00Z',
    formattedDate: 'Sunday, Sep 20',
    formattedTime: '11:00 AM - 6:00 PM',
    price: 'Free',
    isFree: true,
    matchScore: 85,
    vibeTags: ['#Artisans', '#FoodTrucks', '#CanalWalk', '#Screenprinting'],
    organizerName: 'Canal Basin Alliance',
    organizerEmail: 'info@canalbasinmarket.org',
    sourceUrl: 'https://canalbasinmarket.org/fall-makers-grove',
    firecrawlExtractedAt: '2 hrs ago',
    ticketsRemaining: undefined,
    coverImage: 'https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?auto=format&fit=crop&w=800&q=80',
    outreachStatus: 'none',
  },
  {
    id: 'evt-6',
    title: 'Resonance: Micro-Brewery Vinyl Session & Tacos',
    category: 'nightlife',
    tagline: 'Local DJs spinning dub, post-punk, and rare grooves on custom horn speakers',
    description: 'An unpretentious gathering at an independent brewery. Fresh rotating pale ales, birria taco popup, and warm vacuum-tube audio setup.',
    venueName: 'Hop & Needle Taproom',
    address: '315 Copper Street',
    distanceKm: 4.1,
    coordinates: { lat: 40.7225, lng: -73.9521 },
    dateTime: '2026-09-19T18:00:00Z',
    formattedDate: 'Saturday, Sep 19',
    formattedTime: '6:00 PM - 12:00 AM',
    price: 'Free entry',
    isFree: true,
    matchScore: 88,
    vibeTags: ['#Vinyl', '#PostPunk', '#CraftBeer', '#Tacos'],
    organizerName: 'Marcus Brandt',
    organizerEmail: 'marcus@hopneedlebrewing.com',
    sourceUrl: 'https://hopneedlebrewing.com/events/vinyl-session-sep',
    firecrawlExtractedAt: '3 hrs ago',
    ticketsRemaining: undefined,
    coverImage: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=800&q=80',
    outreachStatus: 'none',
  }
];

export const INITIAL_THREADS: EmailThread[] = [
  {
    id: 'th-1',
    eventId: 'evt-1',
    eventTitle: 'Neon Basement: Underground Indie Showcase',
    organizerName: 'Julian Vance',
    organizerEmail: 'booking@subcellarstudio.org',
    agentEmail: 'scout-alpha@sidedoor.agentmail.to',
    subject: 'Inquiry: Door tickets & set times for Saturday',
    lastMessageAt: '8 mins ago',
    status: 'responded',
    messages: [
      {
        id: 'msg-1',
        sender: 'agent',
        senderName: 'SideDoor Scout AI',
        senderEmail: 'scout-alpha@sidedoor.agentmail.to',
        subject: 'Inquiry: Door tickets & set times for Saturday',
        body: `Hi Julian,\n\nI'm scouting on behalf of a local indie rock enthusiast who noticed the Sub-Cellar Showcase this Saturday (Sep 19). Could you confirm if any door tickets will be held for walk-ups after online RSVP reaches capacity, and when the first band goes on?\n\nBest regards,\nSideDoor Scout Agent`,
        sentAt: '25 mins ago',
      },
      {
        id: 'msg-2',
        sender: 'organizer',
        senderName: 'Julian Vance',
        senderEmail: 'booking@subcellarstudio.org',
        subject: 'Re: Inquiry: Door tickets & set times for Saturday',
        body: `Hey there! Yes, absolutely. We always reserve about 25 tickets at the door on a first-come, first-served basis ($15 cash/Venmo). First band starts promptly at 8:45 PM. Tell your user to arrive by 8:15 PM to ensure a spot!\n\nCheers,\nJulian`,
        sentAt: '8 mins ago',
      },
    ],
  },
];

export const MOCK_CRAWLER_SCRIPTS: ScoutLog[] = [
  {
    id: 'log-1',
    timestamp: '11:14:02',
    level: 'info',
    message: 'Scout session started for query: "indie rock shows, outdoor markets, or art openings this weekend within 20 km"',
  },
  {
    id: 'log-2',
    timestamp: '11:14:04',
    level: 'scrape',
    message: 'Firecrawl Search: querying https://api.firecrawl.dev/v1/search for local DIY calendars & venue sitemaps',
    details: 'Discovered 14 potential source URLs across Brooklyn, Lower East Side, and Long Island City.',
  },
  {
    id: 'log-3',
    timestamp: '11:14:07',
    level: 'scrape',
    message: 'Firecrawl Scrape: parsing markdown content from https://subcellarstudio.org/calendar/sep-19-indie-showcase',
    details: 'Extracted raw markdown (3,420 tokens) with band lineup, ticket pricing, and contact email.',
  },
  {
    id: 'log-4',
    timestamp: '11:14:09',
    level: 'ai',
    message: 'AI Evaluation: OpenAI model scoring extracted events against user preferences',
    details: 'Neon Basement scored 98% (Matches tags: indie rock, DIY, basement venue, high local relevance).',
  },
  {
    id: 'log-5',
    timestamp: '11:14:12',
    level: 'mail',
    message: 'AgentMail: Verified agent mailbox scout-alpha@sidedoor.agentmail.to ready for automated organizer outreach',
  },
  {
    id: 'log-6',
    timestamp: '11:14:15',
    level: 'success',
    message: 'Continuous discovery cycle synced with Convex database. 6 verified events matched within 20km.',
  },
];
